version: "3.8"

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "2181:2181"

    kafka-broker:
        image: confluentinc/cp-kafka:latest
        container_name: kafka-broker
        depends_on:
            - zookeeper
        ports:
            - "9092:9092" # Internal listener
            - "9094:9094" # External listener
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

            # Define multiple listeners
            KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker:9092,EXTERNAL://localhost:9094

            # Map listener names to security protocols
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

            # Specify which listener is for inter-broker communication
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    kafka-connect:
        image: confluentinc/cp-kafka-connect:latest
        container_name: kafka-connect
        depends_on:
            - kafka-broker
        ports:
            - "8083:8083"
        environment:
            CONNECT_BOOTSTRAP_SERVERS: kafka-broker:9092
            CONNECT_REST_PORT: 8083
            CONNECT_REST_ADVERTISED_HOST_NAME: localhost
            CONNECT_GROUP_ID: "kafka-connect-group"
            CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
            CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
            CONNECT_STATUS_STORAGE_TOPIC: "connect-statuses"
            CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
            CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
            CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars"
            CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
        volumes:
            - ./connectors:/etc/kafka-connect/jars
        command: >
            bash -c "
            echo 'Waiting for Kafka broker to be ready...';
            cub kafka-ready -b kafka-broker:9092 1 20 &&
            echo 'Kafka broker is ready. Starting Kafka Connect...' &&
            /etc/confluent/docker/run
            "

    mariadb:
        image: mariadb:latest
        container_name: mariadb
        environment:
            - MARIADB_ROOT_PASSWORD=test123
            - MARIADB_DATABASE=experiments
        ports:
            - "3306:3306"
